# Generated by Django 4.1.6 on 2023-02-03 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinggroup',
            name='members',
            field=models.ManyToManyField(related_name='reading_group_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
