# Generated by Django 4.1.6 on 2023-02-10 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_library_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
