# Generated by Django 4.1.6 on 2023-02-03 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_readinggroup_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_title',
            new_name='title',
        ),
    ]
