# Generated by Django 4.1.5 on 2023-02-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_book_title_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='created_at',
        ),
    ]
