# Generated by Django 4.1.6 on 2023-02-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_book_title_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='library',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='library',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
