# Generated by Django 4.1.6 on 2023-02-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_book_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
