# Generated by Django 4.1.6 on 2023-02-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_genre_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='book',
        ),
        migrations.AddField(
            model_name='reservation',
            name='book_library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.booklibrary'),
            preserve_default=False,
        ),
    ]
